name: Update Leaderboard
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Create new readme
        run: python src/build_table.py
      
      - name: push changes
        uses: actions/checkout@v3
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update board"
          git push

